@portURL = http://localhost:5008

GET {{portURL}}/api/qualifications
Accept: application/json

###
POST {{portURL}}/api/qualifications
Content-Type: application/json
Accept: application/json

{
  "name": "Truck Driver",
  "code": "TRD-11"
}

###
GET {{portURL}}/api/VesselType
Accept: application/json

###
GET {{portURL}}/api/VesselType/id/b928c0c9-90c8-4e41-9a6d-59ec1ffef048
Accept: application/json

###
GET {{portURL}}/api/VesselType/name/Panamax
Accept: application/json

###
GET {{portURL}}/api/VesselType/description/size vessel
Accept: application/json

###
GET {{portURL}}/api/vesseltype/filter?name=pan
Accept: application/json

###
GET {{portURL}}/api/vesseltype/filter?description=medium
Accept: application/json

###
GET {{portURL}}/api/vesseltype/filter?query=feed
Accept: application/json

###
POST {{portURL}}/api/VesselType
Content-Type: application/json
Accept: application/json

{
  "name": "Panamax",
  "description": "Medium size vessel",
  "maxBays": 20,
  "maxRows": 15,
  "maxTiers": 10
}



###
GET {{portURL}}/api/Vessel
Accept: application/json

###
GET {{portURL}}/api/Vessel/id/cbfa5eb4-7d11-4032-baeb-c2bdaa888ce6
Accept: application/json

###
GET {{portURL}}/api/Vessel/imo/imo 9706906 
Accept: application/json

###
GET {{portURL}}/api/Vessel/name/Ever Given
Accept: application/json

###
GET {{portURL}}/api/Vessel/owner/Evergreen Marinee
Accept: application/json

###
PATCH http://localhost:5008/api/vessel/imo/IMO 9319466
Content-Type: application/json

{
  "owner": "Evergreen Marine Ltdddd",
  "name" : "Jo"
}


###
POST {{portURL}}/api/Vessel
Content-Type: application/json
Accept: application/json

{
  "imoNumber": "IMO 9319466",
  "name": "Ever Given",
  "owner": "Evergreen Marine",
  "vesselTypeId": "b928c0c9-90c8-4e41-9a6d-59ec1ffef048"
}

###
POST {{portURL}}/api/Vessel
Content-Type: application/json
Accept: application/json

{
  "imoNumber": "9399014",
  "name": "MSC Gulsun",
  "owner": "Mediterranean Shipping Company",
  "vesselTypeId": "b928c0c9-90c8-4e41-9a6d-59ec1ffef048"
}

###
POST {{portURL}}/api/Vessel
Content-Type: application/json
Accept: application/json

{
  "imoNumber": "IMO 9706901",
  "name": "OOCL Hong Kong",
  "owner": "OOCL",
  "vesselTypeId": "c7798221-c758-47fd-a343-21d49b78c806"
}

### --- STAFF MEMBERS ---

###
GET {{portURL}}/api/StaffMembers
Accept: application/json

###
GET {{portURL}}/api/StaffMembers/a0f285f4-b361-4ca5-a31f-1bfc0ad34f54
Accept: application/json

###
GET {{portURL}}/api/StaffMembers/mec/1250001
Accept: application/json

###
GET {{portURL}}/api/StaffMembers/name/Paulo Mendes Updated
Accept: application/json

###
GET {{portURL}}/api/StaffMembers/status/true
Accept: application/json

###
POST {{portURL}}/api/StaffMembers
Content-Type: application/json
Accept: application/json

{
  "shortName": "Paulo Mendes",
  "email": { "address": "mendy@gmail.com" },
  "phone": { "number": "+351912345678" },
  "schedule": { "shift": "Morning", "days": 31 },
  "isActive": true,
  "qualificationIds": ["274b013d-da0d-4e9b-8b83-73c019ce8104"]
}

###
PATCH {{portURL}}/api/StaffMembers/a0f285f4-b361-4ca5-a31f-1bfc0ad34f54
Content-Type: application/json
Accept: application/json

{
  "shortName": "Paulo Mendes Updated",
  "email": { "address": "mendy-updated@gmail.com" }
}

###
PATCH {{portURL}}/api/StaffMembers/a0f285f4-b361-4ca5-a31f-1bfc0ad34f54/toggle
Accept: application/json
