@portURL = http://localhost:5008

GET {{portURL}}/api/qualifications
Accept: application/json

###
POST {{portURL}}/api/qualifications
Content-Type: application/json
Accept: application/json

{
  "name": "Truck Driver",
  "code": "TRD-11"
}

###
GET {{portURL}}/api/VesselType
Accept: application/json

###
GET {{portURL}}/api/VesselType/a26f724a-b072-47db-b492-a02364408ff7
Accept: application/json

###
POST {{portURL}}/api/VesselType
Content-Type: application/json
Accept: application/json

{
  "name": "Panamax",
  "description": "Medium size vessel",
  "maxBays": 20,
  "maxRows": 15,
  "maxTiers": 10
}


###
GET {{portURL}}/api/StaffMembers
Accept: application/json

###
POST {{portURL}}/api/StaffMembers
Content-Type: application/json
Accept: application/json

{
  "id": "d1234567-89ab-cdef-0123-456789abcdef",
  "shortName": "Paulo Mendes",
  "mecanographicNumber": "125001",
  "email": { "address": "mendy@gmail.com" },
  "phone": { "number": "+351912345678" },
  "schedule": { "shift": "Morning", "days": 31 },
  "isActive": true
}
