@portURL = http://localhost:5008

GET {{portURL}}/api/qualifications
Accept: application/json

###
POST {{portURL}}/api/qualifications
Content-Type: application/json
Accept: application/json

{
  "name": "Xu Quer Rola"
}

###
PATCH {{portURL}}/api/qualifications/0d868c4e-2c92-4d4d-9cab-70c549e839d0
Content-Type: application/json
Accept: application/json

{
  "name": "Rola Operator"
}


### --- VESSEL TYPE ---

###
GET {{portURL}}/api/VesselType
Accept: application/json

###
GET {{portURL}}/api/VesselType/id/b928c0c9-90c8-4e41-9a6d-59ec1ffef048
Accept: application/json

###
GET {{portURL}}/api/VesselType/name/Panamax
Accept: application/json

###
GET {{portURL}}/api/VesselType/description/size vessel
Accept: application/json

###
GET {{portURL}}/api/vesseltype/filter?name=pan
Accept: application/json

###
GET {{portURL}}/api/vesseltype/filter?description=medium
Accept: application/json

###
GET {{portURL}}/api/vesseltype/filter?query=feed
Accept: application/json

###
POST {{portURL}}/api/VesselType
Content-Type: application/json
Accept: application/json

{
  "name": "Panamax",
  "description": "Medium size vessel",
  "maxBays": 20,
  "maxRows": 15,
  "maxTiers": 10
}



### --- VESSEL ---


###
GET {{portURL}}/api/Vessel
Accept: application/json

###
GET {{portURL}}/api/Vessel/id/cbfa5eb4-7d11-4032-baeb-c2bdaa888ce6
Accept: application/json

###
GET {{portURL}}/api/Vessel/imo/imo 9706906 
Accept: application/json

###
GET {{portURL}}/api/Vessel/name/Ever Given
Accept: application/json

###
GET {{portURL}}/api/Vessel/owner/Evergreen Marinee
Accept: application/json

###
PATCH http://localhost:5008/api/vessel/imo/IMO 9319466
Content-Type: application/json

{
  "owner": "Evergreen Marine Ltdddd",
  "name" : "Jo"
}

###
POST {{portURL}}/api/Vessel
Content-Type: application/json
Accept: application/json

{
  "imoNumber": "IMO 9319466",
  "name": "Ever Given",
  "owner": "Evergreen Marine",
  "vesselTypeId": "b928c0c9-90c8-4e41-9a6d-59ec1ffef048"
}

###
POST {{portURL}}/api/Vessel
Content-Type: application/json
Accept: application/json

{
  "imoNumber": "9399014",
  "name": "MSC Gulsun",
  "owner": "Mediterranean Shipping Company",
  "vesselTypeId": "b928c0c9-90c8-4e41-9a6d-59ec1ffef048"
}

###
POST {{portURL}}/api/Vessel
Content-Type: application/json
Accept: application/json

{
  "imoNumber": "IMO 9706901",
  "name": "OOCL Hong Kong",
  "owner": "OOCL",
  "vesselTypeId": "c7798221-c758-47fd-a343-21d49b78c806"
}



### --- CONTAINER ---

###
GET {{portURL}}/api/Container
Accept: application/json

###
GET {{portURL}}/api/Container/id/
Accept: application/json

###
GET {{portURL}}/api/Container/iso/
Accept: application/json

###
POST {{portURL}}/api/Container
Content-Type: application/json
Accept: application/json

{
  "isoCode": "MSCU1234567",
  "description": "Standard dry container with electronics",
  "type": "General",
  "weightKg": 12000
}

###
POST {{portURL}}/api/Container
Content-Type: application/json
Accept: application/json

{
  "isoCode": "OOLU7654321",
  "description": "Reefer container for perishable goods",
  "type": "General",
  "weightKg": 8500
}

###
POST {{portURL}}/api/Container
Content-Type: application/json
Accept: application/json

{
  "isoCode": "HLCU9988776",
  "description": "Tank container carrying chemicals",
  "type": "General",
  "weightKg": 14500
}

###
PATCH {{portURL}}/api/Container/update/MSCU1234567
Content-Type: application/json
Accept: application/json

{
  "description": "Dry container updated with fragile electronics"
}


### --- STAFF MEMBERS ---

###
GET {{portURL}}/api/StaffMembers
Accept: application/json

###
GET {{portURL}}/api/StaffMembers/by-qualifications?ids=d3419e74-9413-460e-916f-c420876c5dc6
Accept: application/json


###
GET {{portURL}}/api/StaffMembers/6d5045ef-e932-425f-91cb-becd305312af
Accept: application/json

###
GET {{portURL}}/api/StaffMembers/mec/1250001
Accept: application/json

###
GET {{portURL}}/api/StaffMembers/name/Paulo Mendes
Accept: application/json

###
GET {{portURL}}/api/StaffMembers/status/true
Accept: application/json

###
POST {{portURL}}/api/StaffMembers
Content-Type: application/json
Accept: application/json

{
  "shortName": "Paulo Mendes",
  "email": { "address": "mendy@gmail.com" },
  "phone": { "number": "+351912345678" },
  "schedule": { "shift": "Morning", "days": 31 },
  "isActive": true,
  "qualificationIds": ["d3419e74-9413-460e-916f-c420876c5dc6", "0d868c4e-2c92-4d4d-9cab-70c549e839d0"]
}

###
PATCH {{portURL}}/api/StaffMembers/6d5045ef-e932-425f-91cb-becd305312af
Content-Type: application/json
Accept: application/json

{
  "email": { "address": "mendy-updated@gmail.com" }
}

###
PATCH {{portURL}}/api/StaffMembers/6d5045ef-e932-425f-91cb-becd305312af/toggle
Accept: application/json


### --- DOCK ---
###
GET {{portURL}}/api/Dock
Accept: application/json