// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SEM5_PI_WEBAPI.Infraestructure;

#nullable disable

namespace SEM5_PI_WEBAPI.Migrations
{
    [DbContext(typeof(DddSample1DbContext))]
    [Migration("20251006145951_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("QualificationStaffMember", b =>
                {
                    b.Property<string>("QualificationsId")
                        .HasColumnType("TEXT");

                    b.Property<string>("StaffMemberId")
                        .HasColumnType("TEXT");

                    b.HasKey("QualificationsId", "StaffMemberId");

                    b.HasIndex("StaffMemberId");

                    b.ToTable("StaffMemberQualifications", (string)null);
                });

            modelBuilder.Entity("SEM5_PI_WEBAPI.Domain.Qualifications.Qualification", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Qualifications");
                });

            modelBuilder.Entity("SEM5_PI_WEBAPI.Domain.StaffMembers.StaffMember", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MecanographicNumber")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("StaffMember");
                });

            modelBuilder.Entity("SEM5_PI_WEBAPI.Domain.Vessels.Vessel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VesselTypeId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("VesselTypeId");

                    b.ToTable("Vessel");
                });

            modelBuilder.Entity("SEM5_PI_WEBAPI.Domain.VesselsTypes.VesselType", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<float>("Capacity")
                        .HasColumnType("REAL");

                    b.Property<string>("Description")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("No description");

                    b.Property<int>("MaxBays")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxRows")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxTiers")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("VesselType");
                });

            modelBuilder.Entity("QualificationStaffMember", b =>
                {
                    b.HasOne("SEM5_PI_WEBAPI.Domain.Qualifications.Qualification", null)
                        .WithMany()
                        .HasForeignKey("QualificationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SEM5_PI_WEBAPI.Domain.StaffMembers.StaffMember", null)
                        .WithMany()
                        .HasForeignKey("StaffMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SEM5_PI_WEBAPI.Domain.StaffMembers.StaffMember", b =>
                {
                    b.OwnsOne("SEM5_PI_WEBAPI.Domain.BusinessShared.Schedule", "Schedule", b1 =>
                        {
                            b1.Property<string>("StaffMemberId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Days")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Days");

                            b1.Property<int>("Shift")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Shift");

                            b1.HasKey("StaffMemberId");

                            b1.ToTable("StaffMember");

                            b1.WithOwner()
                                .HasForeignKey("StaffMemberId");
                        });

                    b.OwnsOne("SEM5_PI_WEBAPI.Domain.StaffMembers.Email", "Email", b1 =>
                        {
                            b1.Property<string>("StaffMemberId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("Email");

                            b1.HasKey("StaffMemberId");

                            b1.ToTable("StaffMember");

                            b1.WithOwner()
                                .HasForeignKey("StaffMemberId");
                        });

                    b.OwnsOne("SEM5_PI_WEBAPI.Domain.StaffMembers.PhoneNumber", "Phone", b1 =>
                        {
                            b1.Property<string>("StaffMemberId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("Phone");

                            b1.HasKey("StaffMemberId");

                            b1.ToTable("StaffMember");

                            b1.WithOwner()
                                .HasForeignKey("StaffMemberId");
                        });

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("Phone")
                        .IsRequired();

                    b.Navigation("Schedule")
                        .IsRequired();
                });

            modelBuilder.Entity("SEM5_PI_WEBAPI.Domain.Vessels.Vessel", b =>
                {
                    b.HasOne("SEM5_PI_WEBAPI.Domain.VesselsTypes.VesselType", null)
                        .WithMany()
                        .HasForeignKey("VesselTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("SEM5_PI_WEBAPI.Domain.ValueObjects.ImoNumber", "ImoNumber", b1 =>
                        {
                            b1.Property<string>("VesselId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("ImoNumber");

                            b1.HasKey("VesselId");

                            b1.ToTable("Vessel");

                            b1.WithOwner()
                                .HasForeignKey("VesselId");
                        });

                    b.Navigation("ImoNumber")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
