// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SEM5_PI_WEBAPI.Infraestructure;

#nullable disable

namespace SEM5_PI_WEBAPI.Migrations
{
    [DbContext(typeof(DddSample1DbContext))]
    partial class DddSample1DbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("QualificationStaffMember", b =>
                {
                    b.Property<string>("QualificationsId")
                        .HasColumnType("TEXT");

                    b.Property<string>("StaffMemberId")
                        .HasColumnType("TEXT");

                    b.HasKey("QualificationsId", "StaffMemberId");

                    b.HasIndex("StaffMemberId");

                    b.ToTable("StaffMemberQualifications", (string)null);
                });

            modelBuilder.Entity("SEM5_PI_WEBAPI.Domain.CargoManifestEntries.CargoManifestEntry", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("Bay")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CargoManifestId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContainerId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Row")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StorageAreaId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Tier")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CargoManifestId");

                    b.HasIndex("ContainerId");

                    b.HasIndex("StorageAreaId");

                    b.ToTable("CargoManifestEntries", (string)null);
                });

            modelBuilder.Entity("SEM5_PI_WEBAPI.Domain.CargoManifests.CargoManifest", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("SubmittedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("CargoManifests", (string)null);
                });

            modelBuilder.Entity("SEM5_PI_WEBAPI.Domain.Containers.EntityContainer", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<double>("WeightKg")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Containers", (string)null);
                });

            modelBuilder.Entity("SEM5_PI_WEBAPI.Domain.Dock.Dock", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<double>("DepthM")
                        .HasColumnType("REAL");

                    b.Property<double>("LengthM")
                        .HasColumnType("REAL");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<double>("MaxDraftM")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Dock");
                });

            modelBuilder.Entity("SEM5_PI_WEBAPI.Domain.Qualifications.Qualification", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Qualifications");
                });

            modelBuilder.Entity("SEM5_PI_WEBAPI.Domain.ShippingAgentOrganizations.ShippingAgentOrganization", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AltName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LegalName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("ShippingAgentOrganizations", (string)null);
                });

            modelBuilder.Entity("SEM5_PI_WEBAPI.Domain.ShippingAgentRepresentatives.ShippingAgentRepresentative", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("CitizenId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ShippingAgentRepresentative");
                });

            modelBuilder.Entity("SEM5_PI_WEBAPI.Domain.StaffMembers.StaffMember", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MecanographicNumber")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("TEXT");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("StaffMember");
                });

            modelBuilder.Entity("SEM5_PI_WEBAPI.Domain.StorageAreas.StorageArea", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentCapacityTeu")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxBays")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxRows")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxTiers")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("StorageAreas", (string)null);
                });

            modelBuilder.Entity("SEM5_PI_WEBAPI.Domain.Vessels.Vessel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VesselTypeId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("VesselTypeId");

                    b.ToTable("Vessel");
                });

            modelBuilder.Entity("SEM5_PI_WEBAPI.Domain.VesselsTypes.VesselType", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<float>("Capacity")
                        .HasColumnType("REAL");

                    b.Property<string>("Description")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("No description");

                    b.Property<int>("MaxBays")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxRows")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxTiers")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("VesselType");
                });

            modelBuilder.Entity("QualificationStaffMember", b =>
                {
                    b.HasOne("SEM5_PI_WEBAPI.Domain.Qualifications.Qualification", null)
                        .WithMany()
                        .HasForeignKey("QualificationsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SEM5_PI_WEBAPI.Domain.StaffMembers.StaffMember", null)
                        .WithMany()
                        .HasForeignKey("StaffMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SEM5_PI_WEBAPI.Domain.CargoManifestEntries.CargoManifestEntry", b =>
                {
                    b.HasOne("SEM5_PI_WEBAPI.Domain.CargoManifests.CargoManifest", null)
                        .WithMany("ContainerEntries")
                        .HasForeignKey("CargoManifestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SEM5_PI_WEBAPI.Domain.Containers.EntityContainer", "Container")
                        .WithMany()
                        .HasForeignKey("ContainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SEM5_PI_WEBAPI.Domain.StorageAreas.StorageArea", null)
                        .WithMany()
                        .HasForeignKey("StorageAreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Container");
                });

            modelBuilder.Entity("SEM5_PI_WEBAPI.Domain.Containers.EntityContainer", b =>
                {
                    b.OwnsOne("SEM5_PI_WEBAPI.Domain.ValueObjects.Iso6346Code", "ISOId", b1 =>
                        {
                            b1.Property<string>("EntityContainerId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("IsoCode");

                            b1.HasKey("EntityContainerId");

                            b1.ToTable("Containers");

                            b1.WithOwner()
                                .HasForeignKey("EntityContainerId");
                        });

                    b.Navigation("ISOId")
                        .IsRequired();
                });

            modelBuilder.Entity("SEM5_PI_WEBAPI.Domain.Dock.Dock", b =>
                {
                    b.OwnsOne("SEM5_PI_WEBAPI.Domain.ValueObjects.DockCode", "Code", b1 =>
                        {
                            b1.Property<string>("DockId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("Code");

                            b1.HasKey("DockId");

                            b1.HasIndex("Value")
                                .IsUnique();

                            b1.ToTable("Dock");

                            b1.WithOwner()
                                .HasForeignKey("DockId");
                        });

                    b.OwnsMany("SEM5_PI_WEBAPI.Domain.VesselsTypes.VesselTypeId", "AllowedVesselTypeIds", b1 =>
                        {
                            b1.Property<string>("DockId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .HasColumnType("TEXT")
                                .HasColumnName("VesselTypeId");

                            b1.HasKey("DockId", "Value");

                            b1.ToTable("DockAllowedVesselTypes", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("DockId");
                        });

                    b.Navigation("AllowedVesselTypeIds");

                    b.Navigation("Code")
                        .IsRequired();
                });

            modelBuilder.Entity("SEM5_PI_WEBAPI.Domain.ShippingAgentOrganizations.ShippingAgentOrganization", b =>
                {
                    b.OwnsOne("SEM5_PI_WEBAPI.Domain.ValueObjects.TaxNumber", "Taxnumber", b1 =>
                        {
                            b1.Property<string>("ShippingAgentOrganizationId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("CountryCode")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("TaxNumber");

                            b1.HasKey("ShippingAgentOrganizationId");

                            b1.ToTable("ShippingAgentOrganizations");

                            b1.WithOwner()
                                .HasForeignKey("ShippingAgentOrganizationId");
                        });

                    b.Navigation("Taxnumber")
                        .IsRequired();
                });

            modelBuilder.Entity("SEM5_PI_WEBAPI.Domain.StaffMembers.StaffMember", b =>
                {
                    b.OwnsOne("SEM5_PI_WEBAPI.Domain.BusinessShared.Schedule", "Schedule", b1 =>
                        {
                            b1.Property<string>("StaffMemberId")
                                .HasColumnType("TEXT");

                            b1.Property<int>("Days")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Days");

                            b1.Property<int>("Shift")
                                .HasColumnType("INTEGER")
                                .HasColumnName("Shift");

                            b1.HasKey("StaffMemberId");

                            b1.ToTable("StaffMember");

                            b1.WithOwner()
                                .HasForeignKey("StaffMemberId");
                        });

                    b.OwnsOne("SEM5_PI_WEBAPI.Domain.StaffMembers.Email", "Email", b1 =>
                        {
                            b1.Property<string>("StaffMemberId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("Email");

                            b1.HasKey("StaffMemberId");

                            b1.ToTable("StaffMember");

                            b1.WithOwner()
                                .HasForeignKey("StaffMemberId");
                        });

                    b.OwnsOne("SEM5_PI_WEBAPI.Domain.StaffMembers.PhoneNumber", "Phone", b1 =>
                        {
                            b1.Property<string>("StaffMemberId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("Phone");

                            b1.HasKey("StaffMemberId");

                            b1.ToTable("StaffMember");

                            b1.WithOwner()
                                .HasForeignKey("StaffMemberId");
                        });

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("Phone")
                        .IsRequired();

                    b.Navigation("Schedule")
                        .IsRequired();
                });

            modelBuilder.Entity("SEM5_PI_WEBAPI.Domain.StorageAreas.StorageArea", b =>
                {
                    b.OwnsMany("SEM5_PI_WEBAPI.Domain.ValueObjects.StorageAreaDockDistance", "DistancesToDocks", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("TEXT");

                            b1.Property<float>("Distance")
                                .HasColumnType("REAL")
                                .HasColumnName("Distance");

                            b1.Property<string>("StorageAreaId")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("StorageAreaId");

                            b1.ToTable("StorageAreaDockDistance");

                            b1.WithOwner()
                                .HasForeignKey("StorageAreaId");

                            b1.OwnsOne("SEM5_PI_WEBAPI.Domain.ValueObjects.DockCode", "Dock", b2 =>
                                {
                                    b2.Property<Guid>("StorageAreaDockDistanceId")
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasColumnType("TEXT")
                                        .HasColumnName("DockCode");

                                    b2.HasKey("StorageAreaDockDistanceId");

                                    b2.ToTable("StorageAreaDockDistance");

                                    b2.WithOwner()
                                        .HasForeignKey("StorageAreaDockDistanceId");
                                });

                            b1.Navigation("Dock")
                                .IsRequired();
                        });

                    b.Navigation("DistancesToDocks");
                });

            modelBuilder.Entity("SEM5_PI_WEBAPI.Domain.Vessels.Vessel", b =>
                {
                    b.HasOne("SEM5_PI_WEBAPI.Domain.VesselsTypes.VesselType", null)
                        .WithMany()
                        .HasForeignKey("VesselTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("SEM5_PI_WEBAPI.Domain.ValueObjects.ImoNumber", "ImoNumber", b1 =>
                        {
                            b1.Property<string>("VesselId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("TEXT")
                                .HasColumnName("ImoNumber");

                            b1.HasKey("VesselId");

                            b1.ToTable("Vessel");

                            b1.WithOwner()
                                .HasForeignKey("VesselId");
                        });

                    b.Navigation("ImoNumber")
                        .IsRequired();
                });

            modelBuilder.Entity("SEM5_PI_WEBAPI.Domain.CargoManifests.CargoManifest", b =>
                {
                    b.Navigation("ContainerEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
