@DecisionAddress = http://localhost:5296
###


GET {{DecisionAddress}}/api/schedule/daily?day=2025-11-25
Accept: application/json

###
GET http://localhost:5008/api/VesselVisitNotification
Accept: application/json