@DecisionAddress = http://localhost:5296

###
GET {{DecisionAddress}}/api/schedule/daily/optimal?day=2025-12-01
Accept: application/json

###
GET {{DecisionAddress}}/api/schedule/daily/greedy?day=2025-12-01
Accept: application/json

###
GET {{DecisionAddress}}/api/schedule/daily/local_search?day=2025-12-01
Accept: application/json

###
# Multi-Crane Comparison
GET {{DecisionAddress}}/api/schedule/daily/multi-crane-comparison?day=2025-12-01&algorithm=local_search
Accept: application/json

###
GET {{DecisionAddress}}/api/schedule/daily/genetic?day=2025-12-01
Accept: application/json

###
GET {{DecisionAddress}}/api/schedule/daily/genetic
    ?day=2025-12-01
    &populationSizeOverride=30
    &generationsOverride=60
    &mutationRateOverride=0.25
    &crossoverRateOverride=0.9
Accept: application/json