@startuml
skinparam actorStyle awesome
autonumber

actor "Logistics Operator" as User
participant "System (SPA)" as System

title SSD - US 4.1.3: Search & List Operation Plans

' Fluxo de Pesquisa com Filtros Opcionais
User -> System : GET /api/operation-plans?startDate={...}&endDate={...}&vessel={...}
note right
  Filters (Optional/Combined):
  - Date Range (Start/End)
  - Vessel Identifier
end note

activate System

alt Success (200 OK)
    ' O Sistema retorna a lista filtrada e, idealmente, ordenada
    System --> User : 200 OK (List of OperationPlanDTO)
   

else Invalid Parameters (400)
    ' Ex: Data inválida
    System --> User : 400 Bad Request

else Unauthorized (401)
    System --> User : 401 Unauthorized

end

deactivate System
@enduml