@api_url = http://localhost:3000/api/vve

### Criar um novo Vessel Visit Execution (VVE)
POST http://localhost:3000/api/vve
Content-Type: application/json

{
  "vvnId": "a3e352fa-415f-4ac7-b9fe-8619fa4dc6c3",
  "actualArrivalTime": "2025-05-20T10:30:00Z",
  "creatorEmail": "emanuel@isep.ipp.pt"
}

### Listar todos os registos de VVE
GET {{api_url}}


### Get by id
GET http://localhost:3000/api/vve/6153757c-4db4-4e7b-bb92-e1eebe2264d3

### Get by code
GET http://localhost:3000/api/vve/code/VVE2025000001

### Get by imo
GET http://localhost:3000/api/vve/imo/9823455

### Get in range
GET http://localhost:3000/api/vve/range?timeStart=1747699200000&timeEnd=1779235200000
