@portURL = http://localhost:5008

GET {{portURL}}/api/qualifications
Accept: application/json

###
GET {{portURL}}/api/qualifications/code/QLF-001
Accept: application/json

###
GET {{portURL}}/api/qualifications/name/Xu Quer Rola
Accept: application/json

###
POST {{portURL}}/api/qualifications
Content-Type: application/json
Accept: application/json

{
  "name": "Qualification 2"
}

###
PATCH {{portURL}}/api/qualifications/0d868c4e-2c92-4d4d-9cab-70c549e839d0
Content-Type: application/json
Accept: application/json

{
  "name": "Qualification 2"
}
