@portURL = http://10.9.23.188

# --- STORAGE AREAS ---

###
# 1. GET all (should return list, even empty)
GET {{portURL}}/api/storageareas
Accept: application/json

###
# 2. GET by Id - Valid (Replace GUID after creating one)
GET {{portURL}}/api/storageareas/id/e4b27a02-9438-40a9-9b23-d34a2e1af9c6
Accept: application/json

###
# 3. GET by Id - Invalid (non-existing GUID)
GET {{portURL}}/api/storageareas/id/09446e3d-ae3f-4ed7-b340-0205a4ef8491
Accept: application/json

###
# 4. GET by Name - Valid
GET {{portURL}}/api/storageareas/name/Yard A
Accept: application/json

###
# 5. GET by Name - Invalid (not found)
GET {{portURL}}/api/storageareas/name/UnknownYard
Accept: application/json

###
# 6. GET Distances by Name - Valid
GET {{portURL}}/api/storageareas/distances?name=Yard c
Accept: application/json

###
# 7. GET Distances by Id - Valid (replace Id)
GET {{portURL}}/api/storageareas/distances?id=f2311cf1-5779-4e61-b466-5661c0ab4f68
Accept: application/json

###
# 8. GET Distances - Invalid (no match)
GET {{portURL}}/api/storageareas/distances?name=UnknownYard
Accept: application/json

###
# 9. POST Create - Valid
POST {{portURL}}/api/storageareas
Content-Type: application/json
Accept: application/json

{
  "name": "Yard 88",
  "description": "Secondary yard near Dock 2",
  "type": "Yard",
  "maxBays": -1,
  "maxRows": 1,
  "maxTiers": 1,
  "distancesToDocks": [
    {"dockCode": "DK-0001", "distance": 300},
    {"dockCode": "DK-0002", "distance": 200},
    {"dockCode": "DK-0003", "distance": 100},
    {"dockCode": "DK-0004", "distance": 150},
    {"dockCode": "DK-0005", "distance": 350}
  ],
  "physicalResources": ["TRUCK-0001"]
}

###
# 10. POST Create - Invalid (Name too short)
POST {{portURL}}/api/storageareas
Content-Type: application/json
Accept: application/json

{
  "name": "Wa",
  "description": "Invalid yard",
  "type": "Yard",
  "maxBays": 2,
  "maxRows": 2,
  "maxTiers": 2,
  "distancesToDocks": [
    {"dockCode": "DK-0001", "distance": 300},
    {"dockCode": "DK-0002", "distance": 200},
    {"dockCode": "DK-0003", "distance": 100},
    {"dockCode": "DK-0004", "distance": 150},
    {"dockCode": "DK-0005", "distance": 350}
  ],
  "physicalResources": []
}

###
# 11. POST Create - Invalid (Description too long)
POST {{portURL}}/api/storageareas
Content-Type: application/json
Accept: application/json

{
  "name": "Yard CC",
  "description": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
  "type": "Yard",
  "maxBays": 2,
  "maxRows": 2,
  "maxTiers": 2,
  "distancesToDocks": [
    {"dockCode": "DK-0001", "distance": 300},
    {"dockCode": "DK-0002", "distance": 200},
    {"dockCode": "DK-0003", "distance": 100},
    {"dockCode": "DK-0004", "distance": 150},
    {"dockCode": "DK-0005", "distance": 350}
  ],
  "physicalResources": []
}

### ------
# 12. POST Create - Invalid (Duplicate Dock Code in same request)
POST {{portURL}}/api/storageareas
Content-Type: application/json
Accept: application/json

{
  "name": "Yard D",
  "description": "Duplicate docks test",
  "type": "Yard",
  "maxBays": 2,
  "maxRows": 2,
  "maxTiers": 2,
  "distancesToDocks": [
    {"dockCode": "DK-0001", "distance": 300},
    {"dockCode": "DK-0002", "distance": 200},
    {"dockCode": "DK-0003", "distance": 100},
    {"dockCode": "DK-0004", "distance": 150},
    {"dockCode": "DK-0005", "distance": 350}
  ],
  "physicalResources": []
}

###
# 13. POST Create - Invalid (Negative distance)
POST {{portURL}}/api/storageareas
Content-Type: application/json
Accept: application/json

{
  "name": "Yard E",
  "description": "Negative distance test",
  "type": "Yard",
  "maxBays": 2,
  "maxRows": 2,
  "maxTiers": 2,
  "distancesToDocks": [
    {"dockCode": "DK-0001", "distance": -300},
    {"dockCode": "DK-0002", "distance": 200},
    {"dockCode": "DK-0003", "distance": 100},
    {"dockCode": "DK-0004", "distance": 150},
    {"dockCode": "DK-0005", "distance": 350}
  ],
  "physicalResources": []
}

###
# 15. GET Physical Resources by Name - Valid
GET {{portURL}}/api/storageareas/physicalresources?name=Warehouse A
Accept: application/json

###
# 16. GET Physical Resources by Id - Valid
GET {{portURL}}/api/storageareas/physicalresources?id=3ef22248-4c27-4c48-933b-c17f0731fc31
Accept: application/json

###
# 17. GET Physical Resources - Invalid
GET {{portURL}}/api/storageareas/physicalresources?name=UnknownYard
Accept: application/json
