@portURL = http://localhost:5008
@contentType = application/json
@accept = application/json

# CREATE a new Vessel Visit Notification
###
POST {{portURL}}/api/VesselVisitNotification
Content-Type: {{contentType}}
Accept: {{accept}}

 {
    "estimatedTimeArrival": "2025-12-01T08:00:00",
    "estimatedTimeDeparture": "2025-12-03T18:00:00",
    "volume": 2000,
    "documents": null,
    "crewManifest": {
      "totalCrew": 15,
      "captainName": "John Smith",
      "crewMembers": [
        {"name": "Carlos Mendes", "role": "Captain", "nationality": "Portugal", "citizenId": "A12345"},
        {"name": "Anna Becker", "role": "SafetyOfficer", "nationality": "Peru", "citizenId": "B98765"}
      ]
    },
    "loadingCargoManifest": {
      "type": "Loading",
      "createdBy": "Agent01@gmail.com",
      "entries": [
        {"bay": 2, "row": 3, "tier": 4, "storageAreaName": "Warehouse B", "container": {"isoCode": "MSCU6639870", "description": "Perishable frozen food cargo", "type": "Hazmat", "weightKg": 10800}},
        {"bay": 3, "row": 1, "tier": 2, "storageAreaName": "Warehouse B", "container": {"isoCode": "BBCU5100617", "description": "Electronics", "type": "General", "weightKg": 4500}}
      ]
    },
    "unloadingCargoManifest": {
      "type": "Unloading",
      "createdBy": "Agent02@gmail.com",
      "entries": [
        {"bay": 1, "row": 2, "tier": 3, "storageAreaName": "Warehouse A", "container": {"isoCode": "BBCU5100617", "description": "Automotive parts", "type": "General", "weightKg": 7000}},
        {"bay": 4, "row": 3, "tier": 5, "storageAreaName": "Yard B", "container": {"isoCode": "CSQU3054383", "description": "Furniture Related", "type": "General", "weightKg": 12000}}
      ]
    },
    "vesselImo": "IMO 9823455",
    "emailSar": "alexandre.silva@gmail.com"
 }
###
# 2 - UPDATE an existing Vessel Visit Notification (editable state)

###
PUT {{portURL}}/api/VesselVisitNotification/6dce6c95-9b5b-40f3-9356-4f4588b211a0/update
Content-Type: {{contentType}}
Accept: {{accept}}

{
  "estimatedTimeArrival": "2025-10-01T10:30:00",
  "estimatedTimeDeparture": "2025-10-04T14:00:00",
  "volume": 2300,
  "vesselImo": "IMO 9876544",
  "listDocks": ["DK-0001"],
  "crewManifest": {
    "totalCrew": 17,
    "captainName": "John Smith",
     "crewManifest": {
      "totalCrew": 15,
      "captainName": "John Smith",
      "crewMembers": [
        {"name": "Carlos Mendes", "role": "Captain", "nationality": "Portugal", "citizenId": "A12345"},
        {"name": "Anna Becker", "role": "SafetyOfficer", "nationality": "Peru", "citizenId": "B98765"}
      ]
    },
  },
  "loadingCargoManifest": null,
  "unloadingCargoManifest": null
}


###
# 3 - SUBMIT Vessel Visit Notification for approval

###
PUT {{portURL}}/api/VesselVisitNotification/cfc62475-41ce-4892-aebc-2e29cfdff2ce/submit
Content-Type: {{contentType}}
Accept: {{accept}}


# 4 - WITHDRAW Vessel Visit Notification (only while editable)

###
PUT {{portURL}}/api/VesselVisitNotification/b8bbb8ac-0739-495c-8e6d-85039f2889eb/withdraw
Content-Type: {{contentType}}
Accept: {{accept}}


# 5 - GET Vessel Visit Notification by ID

###
GET {{portURL}}/api/VesselVisitNotification/id/46d6b08b-feba-43ec-b4ea-d083696301c2
Accept: {{accept}}


# ️6 - PUT Accept VVN

###
PUT {{portURL}}/api/VesselVisitNotification/accept/id/cfc62475-41ce-4892-aebc-2e29cfdff2ce
Accept: {{accept}}

# ️7 - PUT Reject/MarkAsPending VVN

###
PUT {{portURL}}/api/VesselVisitNotification/reject
Content-Type: {{contentType}}
Accept: {{accept}}

{
    "vvnCode": "2025-THPA-000001",
    "reason": "Rejecting the VVN due to inconsistencies found in the estimated time of arrival and departure, which require correction before approval."
}


###
# ️8 - Get InProgress & PendingInformation

### 
GET {{portURL}}/api/VesselVisitNotification/shippingAgentRepresentative/inProgress-pendingInformation/f7135f03-505f-40ec-bf5d-55788109b4d4
    ?specificRepresentative=73fbd011-5c94-4029-8a6b-22c1900a39a2
    &vesselImoNumber=IMO9706906
    &estimatedTimeArrival=2025-10-15T10:00
    &estimatedTimeDeparture=2025-10-15T18:00
Accept: application/json

# ️9 - Get Withdrawn

### 
GET {{portURL}}/api/VesselVisitNotification/shippingAgentRepresentative/withdrawn/72f1d6b2-3475-46b8-bb2c-2cf2b379a913
    ?vesselImoNumber=IMO9088888
    &estimatedTimeArrival=2025-10-15T09:00
Accept: application/json

# ️10 - Get Submitted

### 
GET {{portURL}}/api/VesselVisitNotification/shippingAgentRepresentative/submitted/72f1d6b2-3475-46b8-bb2c-2cf2b379a913
    ?submittedDate=2025-10-10T08:00
    &vesselImoNumber=IMO9000123
Accept: application/json

# ️11 - Get Accepted


### 
GET {{portURL}}/api/VesselVisitNotification/shippingAgentRepresentative/accepted/72f1d6b2-3475-46b8-bb2c-2cf2b379a913
    ?acceptedDate=2025-10-11T14:00
    &submittedDate=2025-10-10T08:00
    &vesselImoNumber=IMO9706906
Accept: application/json


