@portURL = http://localhost:5008

### --- DOCK ---

### Get all
GET {{portURL}}/api/Dock
Accept: application/json

### Get by Id
GET {{portURL}}/api/Dock/id/092a810d-e18e-4b5f-bed7-57022b7ffc10
Accept: application/json

### Get by Code
GET {{portURL}}/api/Dock/code/DK-0001
Accept: application/json

### Get by PhysicalResourceCode
GET {{portURL}}/api/Dock/physical-code/STSCR-0001
Accept: application/json

### Get by VesselType
GET {{portURL}}/api/Dock/vesseltype/f9389848-6bcf-4350-8c2b-1e37d95a64da
Accept: application/json

### Filter
GET {{portURL}}/api/Dock/filter?code=DK-0001&location=Terminal&query=DK
Accept: application/json

### Get by Location
GET {{portURL}}/api/Dock/location?value=Terminal
Accept: application/json

### Create
POST {{portURL}}/api/Dock
Content-Type: application/json
Accept: application/json

{
  "code": "DK-0102",
  "PhysicalResourceCodes": [],
  "location": "Terminal Norte A-3",
  "lengthM": 350.0,
  "depthM": 15.5,
  "maxDraftM": 14.8,
  "allowedVesselTypeNames": ["Panamax"]
}

### Patch
PATCH {{portURL}}/api/Dock/code/DK-0001
Content-Type: application/json
Accept: application/json

{
  "location": "Terminal Norte A-4",
  "depthM": 16.0,
  "physicalResourceCodes": ["ABC-1234", "LMN-0001"],
  "allowedVesselTypeIds": [
    "cfcb725b-a005-4869-b7ab-dded0d0299b8"
  ]
}
