@portURL = http://localhost:5008

### 🟢 Get all resources
GET {{portURL}}/api/PhysicalResource
Accept: application/json


### 🟢 Create new resource
POST {{portURL}}/api/PhysicalResource
Content-Type: application/json
Accept: application/json

{
  "description": "Dock Crane A",
  "operationalCapacity": 25.5,
  "setupTime": 10,
  "physicalResourceType": "Truck",
  "qualificationID": "9c5e3d5a-dd32-4f8b-afc0-9cad22ea21eb"
}


### 🟡 Update resource (example)
PUT {{portURL}}/api/PhysicalResource/{{resourceId}}
Content-Type: application/json
Accept: application/json

{
  "description": "Updated Dock Crane A",
  "operationalCapacity": 28.0,
  "setupTime": 15,
  "status": "UnderMaintenance"
}

