@portURL = http://10.9.21.87:5008
#@portURL = http://localhost:5008

# --- STORAGE AREAS ---

###
# 1. GET all (should return list, even empty)
GET {{portURL}}/api/storageareas
Accept: application/json

###
# 2. GET by Id - Valid (Replace GUID after creating one)
GET {{portURL}}/api/storageareas/id/27ac8087-e4a4-48c7-9bd8-017cf9c1223c
Accept: application/json

###
# 3. GET by Id - Invalid (non-existing GUID)
GET {{portURL}}/api/storageareas/id/00000000-0000-0000-0000-000000000000
Accept: application/json

###
# 4. GET by Name - Valid
GET {{portURL}}/api/storageareas/name/Ware house do romeu
Accept: application/json

###
# 5. GET by Name - Invalid (not found)
GET {{portURL}}/api/storageareas/name/UnknownYard
Accept: application/json

###
# 6. GET Distances by Name - Valid
GET {{portURL}}/api/storageareas/distances?name=Ware house do romeu
Accept: application/json

###
# 7. GET Distances by Id - Valid (replace Id)
GET {{portURL}}/api/storageareas/distances?id=f2311cf1-5779-4e61-b466-5661c0ab4f68
Accept: application/json

###
# 8. GET Distances - Invalid (no match)
GET {{portURL}}/api/storageareas/distances?name=UnknownYard
Accept: application/json

###
# 9. POST Create - Valid
POST {{portURL}}/api/storageareas
Content-Type: application/json
Accept: application/json

{
  "name": "Yard B",
  "description": "Secondary yard near Dock 2",
  "type": "Yard",
  "maxBays": 3,
  "maxRows": 2,
  "maxTiers": 2,
  "distancesToDocks": [
    { "dockCode": "DK-0001", "distanceKm": 0.7 }
  ],
  "physicalResources": ["TRUCK-0001"]
}

###
# 10. POST Create - Invalid (Name too short)
POST {{portURL}}/api/storageareas
Content-Type: application/json
Accept: application/json

{
  "name": "Ware house do romeu",
  "description": "Invalid yard",
  "type": "Yard",
  "maxBays": 2,
  "maxRows": 2,
  "maxTiers": 2,
  "distancesToDocks": [],
  "physicalResources": []
}

###
# 11. POST Create - Invalid (Description too long)
POST {{portURL}}/api/storageareas
Content-Type: application/json
Accept: application/json

{
  "name": "Yard C",
  "description": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
  "type": "Yard",
  "maxBays": 2,
  "maxRows": 2,
  "maxTiers": 2,
  "distancesToDocks": [],
  "physicalResources": []
}

### ------
# 12. POST Create - Invalid (Duplicate Dock Code in same request)
POST {{portURL}}/api/storageareas
Content-Type: application/json
Accept: application/json

{
  "name": "Yard D",
  "description": "Duplicate docks test",
  "type": "Yard",
  "maxBays": 2,
  "maxRows": 2,
  "maxTiers": 2,
  "distancesToDocks": [
    { "dockCode": "DK-0005", "distanceKm": 0.0 },
    { "dockCode": "DK-0001", "distanceKm": 2.2 }
  ],
  "physicalResources": []
}

###
# 13. POST Create - Invalid (Negative distance)
POST {{portURL}}/api/storageareas
Content-Type: application/json
Accept: application/json

{
  "name": "Yard E",
  "description": "Negative distance test",
  "type": "Yard",
  "maxBays": 2,
  "maxRows": 2,
  "maxTiers": 2,
  "distancesToDocks": [
    { "dockCode": "DK-0006", "distanceKm": -1.0 }
  ],
  "physicalResources": []
}

###
# 15. GET Physical Resources by Name - Valid
GET {{portURL}}/api/storageareas/physicalresources?name=Ware house do romeu
Accept: application/json

###
# 16. GET Physical Resources by Id - Valid
GET {{portURL}}/api/storageareas/physicalresources?id=05ddc905-bf4a-43f3-a201-8aa5c2f43199
Accept: application/json

###
# 17. GET Physical Resources - Invalid
GET {{portURL}}/api/storageareas/physicalresources?name=UnknownYard
Accept: application/json
