@portURL = http://localhost:5008

### --- SHIPPING AGENT ORGANIZATION ---

###
GET {{portURL}}/api/ShippingAgentOrganization
Accept: application/json

###
GET {{portURL}}/api/ShippingAgentOrganization/code/1234567890
Accept: application/json

###
GET {{portURL}}/api/ShippingAgentOrganization/legalname/Shipping Co.
Accept: application/json

###
GET {{portURL}}/api/ShippingAgentOrganization/taxnumber/PT123456789
Accept: application/json

###
POST {{portURL}}/api/ShippingAgentOrganization
Content-Type: application/json
Accept: application/json

{
  "shippingOrganizationCode": "1234567890",
  "LegalName": "Shipping Co.",
  "AltName": "Shipping",
  "Address": "R. Dr. António Bernardino de Almeida 431, 4249-015 Porto",
  "Taxnumber": "PT123456789"
}

