@portURL = http://10.9.21.87:5008

# ==========================
#  PHYSICAL RESOURCE
# ==========================


# --- GET (Read) ---

### GET all physical resources
GET {{portURL}}/api/PhysicalResource
Accept: application/json


### GET by Id - valid
GET {{portURL}}/api/PhysicalResource/get/204ecabc-d139-45e3-a652-350b3373e194
Accept: application/json


### GET by Id - not found
GET {{portURL}}/api/PhysicalResource/get/204ecabc-d139-45e3-a652-350b3373e191
Accept: application/json


### GET by Code - valid
GET {{portURL}}/api/PhysicalResource/get/code/TRUCK-0001
Accept: application/json


### GET by Code - invalid (not found)
GET {{portURL}}/api/PhysicalResource/get/code/INVAL-0000
Accept: application/json


### GET by Description - valid
GET {{portURL}}/api/PhysicalResource/get/description/Volvo FH16 Truck
Accept: application/json


### GET by Description - not found
GET {{portURL}}/api/PhysicalResource/get/description/NonExistentDescription
Accept: application/json


### GET by Status - Available
GET {{portURL}}/api/PhysicalResource/get/status/Available
Accept: application/json


### GET by Status - UnderMaintenance
GET {{portURL}}/api/PhysicalResource/get/status/UnderMaintenance
Accept: application/json


### GET by Type - valid
GET {{portURL}}/api/PhysicalResource/get/type/Truck
Accept: application/json


### GET by Type - not found
GET {{portURL}}/api/PhysicalResource/get/type/InvalidType
Accept: application/json


### GET by Qualification - valid
GET {{portURL}}/api/PhysicalResource/get/qualification/a8236cf0-1c4a-4989-8055-63cbdc32ded4
Accept: application/json


### GET by Qualification - not found
GET {{portURL}}/api/PhysicalResource/get/qualification/00000000-0000-0000-0000-000000000000
Accept: application/json



# --- POST (Create) ---

### POST Create - valid
POST {{portURL}}/api/PhysicalResource
Content-Type: application/json
Accept: application/json

{
  "description": "Volvo Truck",
  "operationalCapacity": 25.5,
  "setupTime": 10,
  "physicalResourceType": "Truck",
  "qualificationCode": "TRK-001"
}


### POST Create
POST {{portURL}}/api/PhysicalResource
Content-Type: application/json
Accept: application/json

{
  "description": "Dock Crane B",
  "operationalCapacity": 30.0,
  "setupTime": 8,
  "physicalResourceType": "Forklift"
}


### POST Create - invalid type (enum not found)
POST {{portURL}}/api/PhysicalResource
Content-Type: application/json
Accept: application/json

{
  "description": "Invalid Resource",
  "operationalCapacity": 20,
  "setupTime": 5,
  "physicalResourceType": "INVALID_TYPE",
  "qualificationID": "9c5e3d5a-dd32-4f8b-afc0-9cad22ea21eb"
}



### --- PATCH (Update) ---

### PATCH Update - valid (change description)
PATCH {{portURL}}/api/PhysicalResource/update/7b755299-7660-4bd6-9ff1-ffb80db4700e
Content-Type: application/json
Accept: application/json

{
  "description": "Updated Kalmar Reach Stacker RS450"
}


### PATCH Update - valid (change multiple fields)
PATCH {{portURL}}/api/PhysicalResource/update/7b755299-7660-4bd6-9ff1-ffb80db4700e
Content-Type: application/json
Accept: application/json

{
  "operationalCapacity": 10.0,
  "setupTime": 40,
  "qualificationId": "bbdd37c7-9256-4a8e-8713-6199e5eb13e4"
}


### PATCH Update - invalid field (should fail)
PATCH {{portURL}}/api/PhysicalResource/update/6ad4cf47-a9f2-44da-90cc-e4852a4b07c1
Content-Type: application/json
Accept: application/json

{
  "physicalResourceType": "Forklift"
}


### PATCH Update - non-existing Id
PATCH {{portURL}}/api/PhysicalResource/update/00000000-0000-0000-0000-000000000000
Content-Type: application/json
Accept: application/json

{
  "description": "Ghost Resource"
}



### --- PATCH (Deactivate / Reactivate) ---

### PATCH Deactivate - valid
PATCH {{portURL}}/api/PhysicalResource/deactivate/7b755299-7660-4bd6-9ff1-ffb80db4700e
Accept: application/json
Content-Type: application/json


### PATCH Reactivate - valid
PATCH {{portURL}}/api/PhysicalResource/reactivate/7b755299-7660-4bd6-9ff1-ffb80db4700e
Accept: application/json
Content-Type: application/json


### PATCH Deactivate - not found
PATCH {{portURL}}/api/PhysicalResource/deactivate/00000000-0000-0000-0000-000000000000
Accept: application/json
Content-Type: application/json


### PATCH Reactivate - not found
PATCH {{portURL}}/api/PhysicalResource/reactivate/00000000-0000-0000-0000-000000000000
Accept: application/json
Content-Type: application/json
