#@portURL = http://10.9.21.87:5008
@portURL = http://localhost:5008

### --- CONTAINER ---

###
GET {{portURL}}/api/Container
Accept: application/json

###
GET {{portURL}}/api/Container/id/df19db42-cde4-4714-87be-a430f58bf2f3
Accept: application/json

###
GET {{portURL}}/api/Container/iso/MSCU6639870
Accept: application/json

###
POST {{portURL}}/api/Container
Content-Type: application/json
Accept: application/json

{
  "isoCode": "MSCU6639870",
  "description": "Standard dry container with electronics",
  "type": "General",
  "weightKg": 12000
}

###
POST {{portURL}}/api/Container
Content-Type: application/json
Accept: application/json

{
  "isoCode": "OOLU7654321",
  "description": "Reefer container for perishable goods",
  "type": "General",
  "weightKg": 8500
}

###
POST {{portURL}}/api/Container
Content-Type: application/json
Accept: application/json

{
  "isoCode": "HLCU9988776",
  "description": "Tank container carrying chemicals",
  "type": "General",
  "weightKg": 14500
}

###
PATCH {{portURL}}/api/Container/update/CSQU3054383
Content-Type: application/json
Accept: application/json

{
  "description": "Dry container updated with fragile electronics"
}
