@portURL = http://10.9.21.87:5008

GET {{portURL}}/api/qualifications
Accept: application/json

###
GET {{portURL}}/api/qualifications/code/TRK-001
Accept: application/json

###
GET {{portURL}}/api/qualifications/name/Logistics Coordinator
Accept: application/json

###
POST {{portURL}}/api/qualifications
Content-Type: application/json
Accept: application/json

{
  "code": "DDD-002",
  "name": ""
}

###
PATCH {{portURL}}/api/qualifications/0d868c4e-2c92-4d4d-9cab-70c549e839d0
Content-Type: application/json
Accept: application/json

{
  "name": "Qualification 2"
}
