@portURL = http://10.9.23.188

### --- DOCK ---

### Get all
GET {{portURL}}/api/Dock
Accept: application/json

### Get by Id
GET {{portURL}}/api/Dock/id/0a7671cf-ff93-42e6-95b3-d00946d63273
Accept: application/json

### Get by Code
GET {{portURL}}/api/Dock/code/DK-0001
Accept: application/json

### Get by PhysicalResourceCode
GET {{portURL}}/api/Dock/physical-code/RSTAC-0001
Accept: application/json

### Get all Dock codes tenho q ver
GET {{portURL}}/api/Dock/codes
Accept: application/json

### Get by VesselType
GET {{portURL}}/api/Dock/vesseltype/54a29674-de89-4a74-b47e-ce7338f43831
Accept: application/json

### Filter
GET {{portURL}}/api/Dock/filter?code=DK-0001&vesselTypeId=b928c0c9-90c8-4e41-9a6d-59ec1ffef048&location=Terminal&query=DK
Accept: application/json

### Get by Location
GET {{portURL}}/api/Dock/location?value=Terminal
Accept: application/json

### Create
POST {{portURL}}/api/Dock
Content-Type: application/json
Accept: application/json

{
  "code": "DK-0001",
  "physicalResourceCodes": ["ABC-1234", "XYZ-5678"],
  "location": "Terminal Norte A-3",
  "lengthM": 350.0,
  "depthM": 15.5,
  "maxDraftM": 14.8,
  "allowedVesselTypeIds": [
    "54a29674-de89-4a74-b47e-ce7338f43831"
  ]
}

### Patch
PATCH {{portURL}}/api/Dock/code/DK-0001
Content-Type: application/json
Accept: application/json

{
  "location": "Terminal Norte A-4",
  "depthM": 16.0,
  "physicalResourceCodes": ["ABC-1234", "LMN-0001"],
  "allowedVesselTypeIds": [
    "54a29674-de89-4a74-b47e-ce7338f43831"
  ]
}
