@portURL = http://localhost:5008

### --- STAFF MEMBERS ---

### --- Get All
GET {{portURL}}/api/StaffMembers
Accept: application/json

### --- Get by qualification (at least one of the list)
GET {{portURL}}/api/StaffMembers/by-qualifications
Content-Type: application/json
Accept: application/json

{
  "qualificationsCodes": [
    "QLF-001"
  ]
}

### --- Get by exact qualifications
GET {{portURL}}/api/StaffMembers/by-exact-qualifications
Content-Type: application/json
Accept: application/json

{
  "qualificationsCodes": [
    "QLF-001",
    "QLF-002"
  ]
}


### --- Get by database id
GET {{portURL}}/api/StaffMembers/8977010e-da0b-467d-aea3-3627e7180a2f
Accept: application/json

### --- Get by mec number
GET {{portURL}}/api/StaffMembers/mec/1250001
Accept: application/json

### --- Get by Name
GET {{portURL}}/api/StaffMembers/name/Paulo Mendes
Accept: application/json

### --- Get by status
GET {{portURL}}/api/StaffMembers/status/true
Accept: application/json

### 
POST {{portURL}}/api/StaffMembers
Content-Type: application/json
Accept: application/json

{
  "shortName": "Paulo Mendes",
  "email": "mendy@gmail.com" ,
  "phone": "+351912345678" ,
  "schedule": 
    { 
      "shift": "Morning",
      "daysOfWeek": "0011111"
    },
  "isActive": true,
  "qualificationCodes": ["QLF-001", "QLF-002"]
}


###
PUT {{portURL}}/api/StaffMembers/update
Content-Type: application/json
Accept: application/json

{
  "MecNumber": "1250001",
  "Email": "mendyupdated@gmail.com",
  "Schedule": {
    "Shift": "Morning",
    "DaysOfWeek": "1010101"
  },
  "qualificationCodes": ["QLF-007"],
  "addQualifications" : "false"
}


###
PUT {{portURL}}/api/StaffMembers/toggle/1250001
Accept: application/json
