@portURL = http://10.9.23.188
#@portURL = http://localhost:5008
### --- SHIPPING AGENT ORGANIZATION ---

###
GET {{portURL}}/api/ShippingAgentRepresentative
Accept: application/json

###
GET {{portURL}}/api/ShippingAgentRepresentative/name/Alexandre Silva
Accept: application/json

###
GET {{portURL}}/api/ShippingAgentRepresentative/email/alexandre.silva@gmail.com
Accept: application/json

###
GET {{portURL}}/api/ShippingAgentRepresentative/status/activated
Accept: application/json

###
POST {{portURL}}/api/ShippingAgentRepresentative
Content-Type: application/json
Accept: application/json

{
 "Name": "Alexandre Silva",
  "CitizenId": { "PassportNumber": "111111" },
  "Nationality":  "Portugal",
  "Email": {"Address": "alexandre.silva@gmail.com"},
  "PhoneNumber": {"Number": "+351912345678"},
  "Status": "activated",
  "SAO": "1112223334"
}

###
POST {{portURL}}/api/ShippingAgentRepresentative
Content-Type: application/json
Accept: application/json

{
  "Name": "Beatriz Costa",
  "CitizenId": { "PassportNumber": "222222" },
  "Nationality": "Portugal",
  "Email": {"Address":"beatriz.costa@gmail.com"},
  "PhoneNumber": {"Number": "+351913456789"},
  "Status": "activated",
  "SAO": "2223334445"
}

### Update representative status by name (1)
PATCH {{portURL}}/api/ShippingAgentRepresentative/update/alexandre.silva@gmail.com
Content-Type: application/json
Accept: application/json

{
  "Status": "deactivated"
}

### Update representative status by name (2)
PATCH {{portURL}}/api/ShippingAgentRepresentative/update/alexandre.silva@gmail.com
Content-Type: application/json
Accept: application/json

{
  "Status": "activated"
}

### Update representative email by email (1)
PATCH {{portURL}}/api/ShippingAgentRepresentative/update/alexandre.silva@gmail.com
Content-Type: application/json
Accept: application/json

{
  "Email": {"Address": "alexandre2.silva@gmail.com"}
}

### Update representative email by email (1)
PATCH {{portURL}}/api/ShippingAgentRepresentative/update/alexandre2.silva@gmail.com
Content-Type: application/json
Accept: application/json

{
  "Email": {"Address": "alexandre.silva@gmail.com"}
}


