@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

autonumber

actor "User" as ACTOR
participant ":UI" as UI
participant ":Controller" as CTRL
participant ":RepositoryFactory" as FACTORY
participant "factory\n:RepositoryFactory" as FACTORY_INSTANCE
participant "repository\n:Repository" as REPO
participant "entity\n:Entity" as ENTITY

activate ACTOR

    ACTOR -> UI : requests to register a new entity

    activate UI
        UI -> CTRL** : create

        UI --> ACTOR : request data (attribute)
    deactivate UI

    ACTOR -> UI : provides data (attribute)
    activate UI
        UI --> ACTOR : show data for confirmation
    deactivate UI

    ACTOR -> UI : confirms data
    activate UI
        UI -> CTRL : registerEntity(attribute)
        activate CTRL
            CTRL -> CTRL : getRepository()
            activate CTRL
                CTRL -> FACTORY : getInstance()
                activate FACTORY
                    FACTORY --> CTRL : factory
                deactivate FACTORY

                CTRL -> FACTORY_INSTANCE : getRepository()
                activate FACTORY_INSTANCE
                    FACTORY_INSTANCE --> CTRL : repository
                deactivate FACTORY_INSTANCE

                CTRL --> CTRL : repository
            deactivate CTRL

            CTRL -> REPO : registerEntity(attribute)
            activate REPO
                REPO -> ENTITY** : create

                REPO -> REPO : addEntity(entity)
                activate REPO
                    REPO -> REPO : validateEntity(entity)
                    activate REPO
                        REPO --> REPO
                    deactivate REPO
                deactivate REPO

                REPO --> CTRL : entity
            deactivate REPO

            CTRL --> UI : entity
        deactivate CTRL

        UI --> ACTOR : shows success message
    deactivate UI

deactivate ACTOR

@enduml