@startuml

skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title Generic Domain Model Template

hide circles
hide methods

package "Subsystem" {

    class Manager {
    }

    class Resource {
    }

    class Entity {
    }

    Manager "1" -- "1..*" Resource : manages >
    Entity "1" -- "*" Resource : relates to >
}

@enduml